# Generated by Django 2.1.7 on 2019-07-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190626_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='acmodels',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='tags',
        ),
        migrations.DeleteModel(
            name='terms',
        ),
    ]
