# Generated by Django 2.1.7 on 2019-07-01 09:59

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_auto_20190626_1005'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='terms2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='概词条念')),
                ('content', models.TextField(verbose_name='词条说明')),
                ('source', models.TextField(blank=True, verbose_name='词条来源')),
                ('acmodels', models.ForeignKey(limit_choices_to={'if_intra_ac': True}, on_delete=django.db.models.deletion.CASCADE, to='blog.acmodels')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签')),
            ],
        ),
    ]
