# Generated by Django 2.1.7 on 2019-07-01 10:26

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190701_1826'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acr_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='名称')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='简称')),
            ],
            options={
                'verbose_name': '缩略语分类',
                'verbose_name_plural': '缩略语分类',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='acronyms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='缩略语')),
                ('full_name', models.TextField(verbose_name='英文全称')),
                ('zh_name', models.TextField(verbose_name='中文全称')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='分类', to='terms.acr_category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='term_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='名称')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='简称')),
            ],
            options={
                'verbose_name': '术语分类',
                'verbose_name_plural': '术语分类',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='terms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='词条')),
                ('content', models.TextField(verbose_name='词条说明')),
                ('source', models.TextField(verbose_name='词条来源')),
                ('acmodels', models.ForeignKey(limit_choices_to={'if_intra_ac': True}, on_delete=django.db.models.deletion.CASCADE, related_name='适用机型', to='blog.acmodels')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='分类', to='terms.term_category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签')),
            ],
        ),
        migrations.RemoveField(
            model_name='terms2',
            name='acmodels',
        ),
        migrations.RemoveField(
            model_name='terms2',
            name='tags',
        ),
        migrations.DeleteModel(
            name='terms2',
        ),
    ]
