# Generated by Django 2.1.7 on 2019-07-01 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_auto_20190701_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acr_category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='acronyms',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='acr_category', to='terms.acr_category'),
        ),
        migrations.AlterField(
            model_name='term_category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='terms',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='acr_category', to='terms.term_category'),
        ),
    ]
