# Generated by Django 2.1.7 on 2019-07-01 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0004_auto_20190701_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acronyms',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='acr_category', to='terms.acr_category'),
        ),
    ]
