# Generated by Django 2.1.7 on 2019-07-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0006_auto_20190701_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acronyms',
            options={'ordering': ('name',), 'verbose_name': '缩略语', 'verbose_name_plural': '缩略语'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'ordering': ('title',), 'verbose_name': '术语', 'verbose_name_plural': '术语'},
        ),
    ]
