# Generated by Django 2.1.7 on 2019-07-02 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fm',
            name='acmodels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fm_acmodels', to='reac.acmodels'),
        ),
    ]
